apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-sc
spec: 
  accessModes: 
    - ReadWriteMany
  capacity: 
    storage: 1Gi
  nfs: 
    path: /k8nfs
    server: ntnx-nfs-1.citiuscloud.com
  storageClassName: nutanix-dynamicfile
