kind: PersistentVolumeClaim
apiVersion: v1
metadata:
        name: nfspvc
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 3Gi
   storageClassName: dyn-files

