apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: pv-application
spec:
  storageClassName: dyn-files
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

