allowVolumeExpansion: true
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: ntnx-files-sc
provisioner: csi.nutanix.com
parameters:
    csi.storage.k8s.io/node-publish-secret-name: pe-files-secret
    csi.storage.k8s.io/node-publish-secret-namespace: kube-system
    csi.storage.k8s.io/controller-expand-secret-name: pe-files-secret
    csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
    dynamicProv: ENABLED
    nfsServerName: 10.48.71.221
    nfsPath: /k8nfs
    csi.storage.k8s.io/provisioner-secret-name: pe-files-secret
    csi.storage.k8s.io/provisioner-secret-namespace: kube-system
    storageType: NutanixFiles
    squashType: root-squash
